# Generated by Django 3.2.15 on 2022-09-18 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_name', to='meal.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25, unique=True)),
                ('meal_options', models.ManyToManyField(blank=True, to='mealplanner.MealOption')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plans', models.ManyToManyField(blank=True, to='mealplanner.MealPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_planner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_planner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meal_planner', to='mealplanner.mealplanner'),
        ),
        migrations.AddField(
            model_name='mealoption',
            name='meal_plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='mealplanner.mealplan'),
        ),
    ]
