# Generated by Django 3.2.15 on 2022-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='meal_options',
            field=models.ManyToManyField(blank=True, to='mealplanner.MealOption'),
        ),
        migrations.AlterField(
            model_name='mealplanner',
            name='meal_plans',
            field=models.ManyToManyField(blank=True, to='mealplanner.MealPlan'),
        ),
    ]
