# Generated by Django 3.2.15 on 2022-09-19 02:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mealplanner', '0002_alter_mealplan_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('day_one', models.DateField(blank=True, null=True)),
                ('day_two', models.DateField(blank=True, null=True)),
                ('day_three', models.DateField(blank=True, null=True)),
                ('day_four', models.DateField(blank=True, null=True)),
                ('day_five', models.DateField(blank=True, null=True)),
                ('day_six', models.DateField(blank=True, null=True)),
                ('day_seven', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
