# Generated by Django 3.2.15 on 2022-09-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
        ('mealplanner', '0003_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealoptiontomealplan',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.meal'),
        ),
        migrations.AddField(
            model_name='mealoptiontomealplan',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.meal'),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_options',
            field=models.ManyToManyField(blank=True, through='mealplanner.MealOptionToMealPlan', to='meal.Meal'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_options',
            field=models.ManyToManyField(blank=True, through='mealplanner.MealOptionToMealPlan', to='meal.Meal'),
        ),
        migrations.DeleteModel(
            name='MealOption',
        ),
    ]
