# Generated by Django 3.2.15 on 2022-09-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20220913_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.diet'),
        ),
    ]
